### ISSUE TITLE
Fix rake tests failing at Rubocop

### ISSUE THREAD

**Issue by opoudjis** [metanorma/suma#14]
The latest release appears to have been blocked... by Rubocop?!

https://github.com/metanorma/suma/actions/runs/11416570060/job/31767923280

**Comment by ronaldtse** [comment]
You've mistaken. The action you quoted is for testing, not release.

**Comment by CAMOBAP** [comment]
@ronaldtse release is blocked because rake has failed

@opoudjis If a release is needed ASAP, you can always run the release flow manually and it will try to push the current version

I am working on fixing Robocop and adding some base unit tests

**Comment by opoudjis** [comment]
I did do a manual release, and so did Ronald before that.

The problem here is that the people who implemented this gem, who are not me, did not bother to write any rake tests.

**Comment by ronaldtse** [comment]
Closing due to #15.
